src/Entity/Annonces.php
<?php

namespace App\Entity;

use App\Repository\AnnoncesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass=AnnoncesRepository::class)
 * @ORM\Table(name="annonces", indexes={@ORM\Index(columns={"title", "content"}, flags={"fulltext"})})
 */
class Annonces
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime_immutable")
     */
    private $create_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    /**
     * @ORM\ManyToOne(targetEntity=Categories::class, inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity=Images::class, mappedBy="annonces", orphanRemoval=true, cascade={"persist"})
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="annonces", orphanRemoval=true)
     */
    private $comments;



    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }


    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->create_at;
    }


    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getUsers(): ?users
    {
        return $this->users;
    }

    public function setUsers(?users $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function getCategories(): ?categories
    {
        return $this->categories;
    }

    public function setCategories(?categories $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    /**
     * @return Collection|Images[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        //  si l'annonce ne contient pasd'image
        if (!$this->images->contains($image)) {
            // je place l'objet image ds le tableau images
            $this->images[] = $image;
            // à cet objet Image ajoute moi "l'annonce"
            $image->setAnnonces($this);
        }
        // RETOURNE L'ANNONCE
        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAnnonces() === $this) {
                $image->setAnnonces(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAnnonces($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAnnonces() === $this) {
                $comment->setAnnonces(null);
            }
        }

        return $this;
    }
}

src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;



/**
 * @ORM\Entity(repositoryClass=CommentsRepository::class)
 */
class Comments
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active = true;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nickname;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $rgpd;

    /**
     * @ORM\ManyToOne(targetEntity=Annonces::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $annonces;

    /**
     * @ORM\ManyToOne(targetEntity=Comments::class, inversedBy="replies")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="parent")
     */
    private $replies;

    public function __construct()
    {
        $this->replies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    public function setNickname(string $nickname): self
    {
        $this->nickname = $nickname;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getRgpd(): ?bool
    {
        return $this->rgpd;
    }

    public function setRgpd(bool $rgpd): self
    {
        $this->rgpd = $rgpd;

        return $this;
    }

    public function getAnnonces(): ?Annonces
    {
        return $this->annonces;
    }

    public function setAnnonces(?Annonces $annonces): self
    {
        $this->annonces = $annonces;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getReplies(): Collection
    {
        return $this->replies;
    }

    public function addReply(self $reply): self
    {
        if (!$this->replies->contains($reply)) {
            $this->replies[] = $reply;
            $reply->setParent($this);
        }

        return $this;
    }

    public function removeReply(self $reply): self
    {
        if ($this->replies->removeElement($reply)) {
            // set the owning side to null (unless already changed)
            if ($reply->getParent() === $this) {
                $reply->setParent(null);
            }
        }

        return $this;
    }
}

src/Form/AnnoncesType.php
<?php

namespace App\Form;

use App\Entity\Annonces;
use App\Entity\Categories;
use Symfony\Component\Form\AbstractType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;


class AnnoncesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class)
            ->add('content', CKEditorType::class )
            ->add('categories', EntityType::class, [
                'class' => Categories::class,
            ])
            // On ajoute le champ "images" ds le formulaire dans le formulaire
            // il n'est pas lié à la BDD (mapped à false)

            ->add('images', FileType::class, [
                'label' => false,
                'multiple' => true,
                'mapped' => false,
                'required' => false
            ])
            // ->add('created_at')
            ->add('Valider', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Annonces::class,
        ]);
    }
}

src/Controller/Admin/AnnoncesController.php
<?php

namespace App\Controller\Admin;


use App\Entity\Images;
use App\Entity\Annonces;
use App\Repository\AnnoncesRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


/**
 * @Route("/admin/annonces", name="admin_annonces_")
 * @package App\Controller\Admin
 */


class AnnoncesController extends AbstractController
{
    /**
     * @Route("/", name="home")    
     * 
     */
    public function index(AnnoncesRepository $annoncesRepo): Response
    {
        return $this->render('admin/annonces/index.html.twig', [
            'annonces' => $annoncesRepo->findAll(),
        ]);        
    }

    
    /**
     * @Route("/activer/{id}", name="activer")    
     * 
     */
    public function activer(Annonces $annonce, ManagerRegistry $doctrine)
    {
        // en ajax 
        $annonce->setActive(($annonce->getActive()) ? false : true);

        $em = $doctrine->getManager();
        // persist = ajouter
        $em->persist($annonce);
        $em->flush();
        return new Response("true");
    }

    /**
     * @Route("/supprimer/{id}", name="supprimer")    
     * 
     */
    public function supprimer(Annonces $annonce, ManagerRegistry $doctrine)
    {
        // en ajax 
        // $annonce->setActive(($annonce->getActive())? false : true);

        $em = $doctrine->getManager();
        // persist = ajouter
        $em->remove($annonce);
        $em->flush();

        $this->addFlash('annonce', "'annonce' {{annonce.title}} 'supprimée'");
        return $this->redirectToRoute('admin_annonces_home');
    }

}

templates/annonces/details.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('detail')}}
{% endblock %}

{% block title %}
	Détail de l'annonce
{% endblock %}

{% block body %}
	<div class="box mx-auto">
		{# ici, je code les msg FlashErrors, je récupère message de AnnonceController ligne 62 #}

		{# <div class="card shadow-1 fx-row grix xs2 sm2 gutter-2"> #}
			<div class="card shadow-1 fx-row grix mt-2"> <div class="primary d-flex vcenter fx-center px-4">
				{# {{dump(annonce.images[0].name)}} #}
				{# {{ dump(annonce.images)}}
				{{ annonce.title }}
				{{ annonce.active }} #}
					{% if annonce.images[0] is defined %}
					{# {{ annonce.images[0].name}}																																													{{ annonce.images[0].id}} #}
				<img src="{{ asset('uploads/images/annonces/' ~ annonce.images[0].name)|imagine_filter('square') }}" alt="{{ annonce.title }}"> {% endif %}
			</div>

			<div class="flex fx-col fx-grow sm2">
				{% for message in app.flashes('message') %}
					<div class="alert_mail p-1 my-2 rounded-1 green txt-dark-4 bd-solid bd-green bd-dark-1 bd-1" role="alert">
						<i class="bi bi-alarm"></i>
						{{ message }}</div>
				{% endfor %}
				<div
					class="card-header">
					{# {{annonce.id}} #}
					<strong>{{ annonce.title|upper }}</strong>
					<br/>
					<small>
						<em class="annonce_date">{{annonce.createAt|date("d/m/Y H:i")}}</em>
					</small>
				</div>

				<div class="card-content mx-auto">
					<p>Catégorie :
						{{ annonce.categories.name }}
					</p>
					{# striptags est un filtre de Twig #}
					<p>Description :
						{# {{ dump(annonce)}}
						{{ dump(annonce.content)}} #}
						{# {{annonce.content}} #}
						{# {{annonce.content|raw}} #}
						{# le filtre raw élimine les balises ds le texte #}
						{{ annonce.content|raw}}
						{# {{annonce.content|replace({'|': "-", "," : "."})}} #}
						<pre>
							{# {{ dump(annonce.content) }} #}
						</pre>
					</p>
					{# ici, le bouton qui appelle  ma modale "contactez-l'annonceur #}
				<button class="btn rounded-1 primary press modal-trigger mt-3" data-target="modal-example"> Contacter l'annonceur</button>
				</div>


				{# ici, le code des commentaires **********************COMMENTAIRES**************************** dans ma page detail/{id} #}
				<div class="grix xs2 sm3 gutter-0 card p-3 m-0">
				<div class="col-xs2 col-sm3">
					<h2>Liste des commentaires</h2>
					{# je vais chercher les com de l'annonce concernée #}
					{% for comment in annonce.comments %}
						{# si comment.parent est null, alors j'affiche le commentaire et ses réponses. Sinon, rien #}
						{# on affiche en premier lieu, les com où on n'a pas eu de réponse #}
						{% if comment.parent == null %} 
							<h3>Commentaire ( {{loop.index}} ) de {{comment.nickname}} </h3>
							<div class="card bd-blue bd-solid bd-3 p-3 m-0">
								{# {{ dump(comment)}} #}
								<p>Publié par {{ comment.nickname }} le {{comment.createdAt|date("d/m/Y H:i")}}  </p>
								<div> {{comment.content|replace({'<script>': "__", "," : "."}) }}
								{# {{ dump(comment.content) }} #}
								</div>
								{# data-reply va permettre d'écouter l'événement #}
								{# avec data-id, je récupère le numéro du commmentaire auquel je réponds #}
								<p> <a href="#" data-reply data-id="{{comment.id}}" class="btn rounded-1 primary press modal-trigger m-0 mt-1">Répondre à ce commentaire </a> </p>
									
								{# on affiche les réponses au commentaire #}
								{% for reply in comment.replies %}
									<p>Réponse publiée par {{ reply.nickname }} le {{reply.createdAt|date("d/m/Y H:i")}}  </p>
									<div> {{reply.content|raw}} </div>
																
								{% endfor %}
							</div>
						{% endif %}	
					{% endfor %}
				</div>
			</div>
				<div class="col-xs2 col-sm3" id="ajout-commentaire">
					<h2>Ajouter un commentaire</h2>
					{# je récupére le formulaire créé à la ligne 240 de Annonces.Controller.php #}
					{{ form(commentform) }}
				</div>
			</div>			
		</div>


		{# ici le code du caroulix ********************************************************************************************
										******CAROULIX *******************************************************************************************************************#}
		<div class="caroulix" id="second-caroulix" data-ax="caroulix" data-caroulix-indicators-enabled="true" data-caroulix-indicators-is-flat="true">

			{% for image in annonce.images %}
				<div
					class="caroulix-item mt-1">
					{# banniere est le filtre codé ds liip_imagine.yaml dossier package/tests #}
					<img src="{{ asset('uploads/images/annonces/' ~ image.name)|imagine_filter('banniere') }}" alt="{{ annonce.title }}" class="caroulix_img"/>
				</div>
			{% endfor %}

		</div>
		<div
			class="caroulix_button d-flex fx-center mt-2">
			{# si mon array contient moins de 2 images, je "cache" les deux boutons #}
			{% if annonce.images|length > 1 %}
				<button onclick="Axentix.getInstance('#second-caroulix').prev()" class="btn primary rounded-1 shadow-1 m-2">PREV</button>
				<button onclick="Axentix.getInstance('#second-caroulix').next()" class="btn primary rounded-1 shadow-1 m-2">NEXT</button>
				{% else %}

			{% endif %}
		</div>
		{# {{ dump(annonce.images)}}
		 {{ annonce.images[0].name}} #}
	</div>

	{# ici, le code de ma modale "contactez-moi" ****************************************************************************************************
					************************************************************************************************************************************#}
	<div class="modal shadow-1 white falling" id="modal-example" data-ax="modal">
		{# {{ dump(annonce.users.lastname)}} #}
		<div class="modal-header">Contacter l'annonceur :<em class="txt-primary">
				{{ annonce.users.firstname}}
				{{ annonce.users.lastname}}
			</em>
		</div>

		<div class="divider"></div>
		{{ form_start(form)}}
		<div class="modal-content">
			{{ form_widget(form.title) }}
			{{ form_row(form.email) }}
			{{ form_row(form.message) }}
			....details.html.twig
			<div class="divider"></div>

			<div class="modal-footer">
				<button class="btn small primary">Envoyer</button>
				<button data-target="modal-example" class="ml-auto btn shadow-1 rounded-1 small primary modal-trigger">Fermer</button>
			</div>
			{{form_end(form)}}

		</div>
	{% endblock %}


	{% block javascripts %}
	{# {{ encore_entry_script_tags('monfichierjs')}} #}
	<script>
	{# écouteur d'événement pour la réponse à un commentaire (tuto 18 : 41mn20) 
	sur tous les boutons réponse. Cet écouteur va surveiller le click #}
	window.onload = () => {
		document.querySelectorAll("[data-reply").forEach(element => {
			element.addEventListener("click", function(){
				console.log(this);
				document.querySelector("#comments_parentid").value = this.dataset.id;
			})
		});
	}
	</script>


	{% endblock %}

templates/annonces/fichiertest.html.twig
{% extends "base.html.twig" %}

{% block title %}
{# {{parent()}} #}
Test
{% endblock %}

{% block stylesheets %}
{{ parent() }}
{# detail.scss doit être déclaré en AddEntry ds Webpack.config #}
{{ encore_entry_link_tags('detail')}} 
{% endblock %}


{% block body %}
{{ parent() }}
<h1>Comment vas-tu?</h1>

{% endblock %}

{% block javascripts %}
{{ parent() }}
{{encore_entry_script_tags('navbar')}}
{% endblock %}

templates/annonces/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}fichier créé lors du "make controller AnnoncesController  Hello AnnoncesController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'D:/CDA/symfonyannonce/annonce/src/Controller/AnnoncesController.php'|file_link(0) }}">src/Controller/AnnoncesController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'D:/CDA/symfonyannonce/annonce/templates/annonces/index.html.twig'|file_link(0) }}">templates/annonces/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}